### ISSUE TITLE
Invalid date-time error when save code changes

### ISSUE THREAD

**Issue by subham6651** [DataFire/DataFire.io-Website#3]
after making changes when i try to save code into git repo it throw error 
"Invalid HTTP response: 422 Invalid request. 2018-01-30T14:26:20+05:0-18 is not a valid date-time. 2018-01-30T14:26:20+05:0-18 is not a valid date-time."

**Comment by rbren** [comment]
Thanks! I think I've finally tracked this down to an [external library](https://github.com/creationix/js-github/pull/21/files). 

It should be fixed on DataFire.io version 2.4.0
