### ISSUE TITLE
Sign in modal displayed on project pages

### ISSUE THREAD

**Issue by jfexyz** [DataFire/DataFire.io-Website#4]
When I visit a URL for a project (or any subpage), e.g. https://app.datafire.io/projects/xyz, I get the "Sign up for DataFire" modal. I have yet to realize this once, and always trigger 1Password to fill the form and submit. In which case I get the error "An account for user@example.com already exists".

A couple of suggestions:

- Default to the "Sign into your DataFire account" modal when visiting a project page (as you might be able to assume it's more likely the user has an account already).
- Or maybe better, combine the Sign up and Sign in forms. Since you're already checking if the user email exists or not, just attempt to authenticate if it does. If it doesn't exist, create the user.

**Comment by rbren** [comment]
That's a good point. Changed to showing the "sign in" modal instead in v2.4.1
